In [9]:
import numpy as np

def convolution(matrix, kernel):
    matrix_height, matrix_width = matrix.shape
    kernel_height, kernel_width = kernel.shape
    output_height = matrix_height - kernel_height + 1
    output_width = matrix_width - kernel_width + 1
    output = np.zeros((output_height, output_width))

    for i in range(output_height):
        for j in range(output_width):
            output[i, j] = np.sum(matrix[i:i+kernel_height, j:j+kernel_width] * kernel)

    return output

matrix = np.array([[1, 1, 1, 0, 0],
                  [0, 1, 1, 1, 0],
                  [0, 0, 1, 1, 1],
                  [0, 0, 1, 1, 0],
                  [0, 1, 1, 0, 0]])

kernel = np.array([[1, 0, 1],
                  [0, 1, 0],
                  [1, 0, 1]])

result = convolution(matrix, kernel)
print(result)

[[4. 3. 4.]
 [2. 4. 3.]
 [2. 3. 4.]]
